### ISSUE TITLE
Feature request: DAM/RT Toggle

### ISSUE THREAD

**Issue by benneiman** [rconcep/snl-quest#7]
Requesting a UI toggle similar to zonal/generator in Data Manager to select DAM/RT pricing. Working with NYISO specifically, default is DAM only and to get RT data had to go set it manually in widgets.py.

Thanks!

**Comment by rconcep** [comment]
Hello,

It would probably be a relatively quick implementation that we can work on. Since none of the other QuESt applications currently use that data, we decided not to implement the interface to download RT prices... likewise for other ISO/RTOs that have a plethora of data available to download.

We are aware that there are many people who would be perfectly happy to have a tool that just grabs data! Therefore, further developing QuESt Data Manager to get more varieties of data is something we can possibly work on but we currently are mostly focusing on the modeling and analysis capabilities.

We'll consider your request as we develop future updates.

**Comment by benneiman** [comment]
Thanks!
